name: meditation_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  just_audio: ^0.10.5
  provider: ^6.1.5+1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/home/
  - assets/images/meditate/
  - assets/images/sleep/
  - assets/images/topic/
  - assets/images/icons/
  - assets/sounds/